<div id="googlesearch">
<!-- Google CSE Search Box Begins -->
NSW Railways Search:
<form id="searchbox_015811549446532285071:_6o5bjxzw2e" action="http://www.google.com/cse">
  <input type="hidden" name="cx" value="015811549446532285071:_6o5bjxzw2e" />
  <input name="q" type="text" size="40" />
  <input type="submit" name="sa" value="Search" />
  <input type="hidden" name="cof" value="FORID:0" />
</form>
<script type="text/javascript" src="http://www.google.com/coop/cse/brand?form=searchbox_015811549446532285071%3A_6o5bjxzw2e"></script>
<!-- Google CSE Search Box Ends -->
<br/>
</div>
