
<h2>Recent Updates</h2>

<div style="height: 250px; overflow:auto;">

<table width="100%" cellspacing="0" cellpadding="5px" border="0">

<tr valign="top">
  <td align="right"><strong>Dec&nbsp;8&nbsp;2005</strong></td>
  <td> Added photos from: Jeff Mullier (Neath, Caledonia, Bellbird Junction), Kevin Jones (Commonwealth Siding, Cheltenham), Bob Bailey (Islington Junction), Judy Brown (Lake Bathurst), Adrian Chippendale (Grenfell), Woodford Academy Photo Collection (Woodford), William Gay (Central), Karina Hall (Potts Hill branch, Regents Park), Grant Miller (Broadmeadow), Stephan Delaney (Canberra, Queanbeyan), Geoff Allcock (Richmond branch, West Wyalong, Wyalong), Alex Li (Corrimal, Bellambi), Stephen Bennetts (Milsons Point, Martin Place, Circular Quay, Central, Windsor, Riverstone), Duncan Butcher (Merrygoen), Garry Sanders (Central), James Maskell (East Maitland, Nimmitabel), Goldfish (Moama, Wakool, Balranald, Moulamein, Moira, Mathoura).</td>
</tr>
		
<tr valign="top">
  <td align="right"><strong>Oct&nbsp;21&nbsp;2005</strong></td>
  <td> Added photos from: Scott McKinnon (historic photos of the Tottenham, Parkes - Narromine lines; Gunningbland, Cowra, Gooloogong, Gilgandra, Baradine, Tichborne, Eumungerie, Coonamble, Coonabarabran), Ross McConchie (Strathfield, Bungendore Junction), Peter Ware (North Coast line, Gosford), Stephan Delaney (South Coast line).</td>
</tr>
		
<tr valign="top">
  <td align="right"><strong>Oct&nbsp;11&nbsp;2005</strong></td>
  <td> Added photos from: Michael Thornes (Tamworth, Glen Innes, Werris Creek, Tenterfield), Kevin Jones (Mount Frome, Mount Knowles), W. Madden (Stockinbingal - Parkes line, Blayney), Bradley Curran (Molong, Kerrs Creek).</td>
</tr>
		
<tr valign="top">
  <td align="right"><strong>Oct&nbsp;8&nbsp;2005</strong></td>
  <td> Added photos from: Kevin Jones (Pipers Flat), James Banks (Branxton), Goldfish (Gadara), Glenn Martin (Kurrajong, Duffys, North Richmond), Dimi Nikolias (Shell Refinery Siding, Sandown), James Maskell (Town Hall), Anonymous01 (Emu Plains, Hardies), Duncan Butcher (Adamstown, Walgett, Bugilbone, Tikkara, Boorindal, Trangie, Baan Baa, Merah North, Jct (Byrock), Cobar, Wave Hill, Burren, Tarcoon, Parkes, Wee Waa, Walgett Wheat Terminal).</td>
</tr>
		
<tr valign="top">
  <td align="right"><strong>Sep&nbsp;28&nbsp;2005</strong></td>
  <td> Added photos from: James Banks (Lochinvar), Jeff Kaye (Wallerawang), Duncan Butcher (Tottenham line, Bogan Gate - Ivanhoe).</td>
</tr>
		
<tr valign="top">
  <td align="right"><strong>Sep&nbsp;24&nbsp;2005</strong></td>
  <td> Fixed broken links on the master photograph index. Added more photos from: Goldfish (Sheahan), myself (Wallerawang Colliery and Oaklands branches, Newnes Junction to Wallerawang, Cullen Bullen, Moama).</td>
</tr>
		
</table>
<a href="/updates.html">(more...)</a>
</div>
	