<br/>
<a href="/lines/main_west/photos/dubbo06.html"><img src="/images/random/randpic11408904101.jpg" border="1" width="128" height="85" alt="[random rail image]"></img></a><br />
<br/>
<a href="/lines/gwabegar/photos/ben_bullen02.html"><img src="/images/random/randpic11408904102.jpg" border="1" width="128" height="85" alt="[random rail image]"></img></a><br />
<br/>
<a href="/lines/main_west/photos/narromine01.html"><img src="/images/random/randpic11408904103.jpg" border="1" width="128" height="85" alt="[random rail image]"></img></a><br />
<br/>
<a href="/lines/lake_cargelligo/photos/reefton02.html"><img src="/images/random/randpic11408904104.jpg" border="1" width="128" height="85" alt="[random rail image]"></img></a><br />
<br/>
<a href="/lines/wardell_road_central/photos/darling_harbour13.html"><img src="/images/random/randpic11408904105.jpg" border="1" width="128" height="85" alt="[random rail image]"></img></a><br />
