<div class="navbar">
<table>
<tr>
<td><a href="/index.html">Home</a></td>
<td><a href="/lines/nsw-map.php">Lines</a></td>
<td><a href="/photos/index.php">Photos</a></td>
<td><a href="/maps/index.php">Maps</a></td>
<td><a href="/infrastructure/index.php">Infrastructure</a></td>
<td><a href="/trivia/index.php">Trivia</a></td>
<td><a href="/library/index.php">Library</a></td>
<td><a href="/links/index.php">Links</a></td>
<td><a href="/about/index.php">About</a></td>
</tr>
</table>
</div>
