<div id="text">
These pages contain a variety of information about the NSW railway network,
both historical and current. The data can be broken down into four
categories: non-spatial (plain data), spatial (map data), photographic
and hypertext (links to related data sources). The intention of these pages
to make as much information as possible available on the net. Although
you will find pictures of trains within these pages, I have chosen to
concentrate on recording the infrastructure of the state, especially
on the abandoned branch lines.
</p>
<p>
Much as I would like to, I probably won't be able to visit every
location in the state, taking notes and photographs! If you want to
contribute information or photos, then please contact me at
<a href="mailto:nswrail@pobox.com">nswrail@pobox.com</a>.
</p>
<p>
Much of the information and photos in these pages has been generously
provided by a lot of people. Their work has contributed immeasureably to
the success of these pages.
</p>
<p>
<b>Rolfe Bozier</b>
</p>
<img src="/images/nswrail-logo-medium.png" alt="NSWrail.net logo" />
<!--
<p>
P.S. Please don't ask me about travel arrangements, as I can't provide any
advice. You might like to try
<a href="http://www.railpage.org.au/railmaps/">Australian Rail Maps</a>
as a starting point for planning a trip.
</p>
-->
</div>
